apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: texa6a3kq-nodejs-gitops
  description: This is GitOps manifest for texa6a3kq-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=texa6a3kq-nodejs
    backstage.io/kubernetes-id: texa6a3kq-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: texa6a3kq-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:texa6a3kq-nodejs
